#!/bin/bash

mpc-tagrenamevalue COMPOSER "Frédéric Chopin" "Fryderyk Chopin"
mpc-tagrenamevalue COMPOSER "Zbigniew Namyslowski" "Zbigniew Namysłowski"
mpc-tagrenamevalue COMPOSER "Sergei Rachmaninoff" "Sergei Vasilyevich Rachmaninoff"
mpc-tagrenamevalue COMPOSER "Sergey Rachmaninov" "Sergei Vasilyevich Rachmaninoff"
mpc-tagrenamevalue COMPOSER "Сергей Васильевич Рахманинов" "Sergei Vasilyevich Rachmaninoff"
mpc-tagrenamevalue COMPOSER "Sergey Prokofiev" "Sergei Prokofiev"
mpc-tagrenamevalue COMPOSER "Александр Николаевич Скрябин" "Alexander Scriabin"
mpc-tagrenamevalue COMPOSER "Дмитрий Дмитриевич Шостакович" "Dmitri Shostakovich"
mpc-tagrenamevalue COMPOSER "Игорь Фёдорович Стравинский"  "Igor Stravinsky"
mpc-tagrenamevalue COMPOSER "Милий Алексеевич Балакирев"  "Mily Balakirev"
mpc-tagrenamevalue COMPOSER "Модест Петрович Мусоргский" "Modest Mussorgsky"
mpc-tagrenamevalue COMPOSER "Николай Андреевич Римский‐Корсаков" "Nikolai Rimsky-Korsakov"
mpc-tagrenamevalue COMPOSER "Пётр Ильич Чайковский" "Pyotr Il'yich Tchaikovsky"
mpc-tagrenamevalue COMPOSER "Pyotr Il'yich Tchaikovsky" "Pyotr Ilyich Tchaikovsky"
mpc-tagrenamevalue COMPOSER "Рейнгольд Морицевич Глиэр" "Reinhold Glière"
mpc-tagrenamevalue COMPOSER "Сергей Иванович Танеев" "Sergei Taneyev"
mpc-tagrenamevalue COMPOSER "Сергей Сергеевич Прокофьев" "Sergei Prokofiev"
