#!/bin/bash

set -e

FILENAME=`basename "$0"`

if [ "$FILENAME" == "taglintclassical" ]; then
	TAGS=(WORK MOVEMENT MOVEMENTNAME OPUS COMPOSER PERFORMER ENSEMBLE CONDUCTOR RECORDINGLOCATION RECORDINGDATE RATING COMPOSERSORT GENRE)
elif [ "$FILENAME" == "taglintjazz" ]; then
	TAGS=(PERFORMER RECORDINGLOCATION RECORDINGDATE RATING GENRE STYLE)
else
	echo "Please call taglintjazz or taglintclassical, not $0"
fi

function has_tag() {
	TAG="$1"
	FILE="$2"
	if grep -qi "^$TAG=" <(metaflac --export-tags-to=- "$FILE"); then
		return 0
	else
		return 1
	fi
}

for f in "$@"; do
	for t in "${TAGS[@]}"; do
		if ! has_tag "$t" "$f"; then
			echo "$f	$t"
		fi
	done
done

for f in "$@"; do
	metaflac --export-tags-to=- "$f" | sort | uniq -icd | while read line; do
		echo "$f	DUPLICATE: $line"
	done
done

for f in "$@"; do
	metaflac --export-tags-to=- "$f" | grep '[^=]*=\s*$' | while read line; do
		echo "$f	EMPTY: $line"
	done
done
