#!/bin/bash

set -e

TMPFILE=`mktemp /tmp/tagremove.XXXXXX`
WRITE=$1
TAG=$2

if [[ "$WRITE" != "yes" ]] && [[ "$WRITE" != "no" ]]; then
	echo "Arg 1 must be yes or no"
	exit 1
fi

for f in "${@:3}"; do
	metaflac --export-tags-to=$TMPFILE "$f"
	
	if [[ "$WRITE" == "yes" ]]; then
		metaflac --remove-tag="$TAG" "$f"
	else
		grep "^$TAG=" $TMPFILE | while read line; do
			echo Removing "$line"
		done
	fi
done
