#!/bin/bash

set -e

TMPFILE=`mktemp /tmp/tagremove.XXXXXX`
WRITE=$1
TAG=$2
FROM=$3
TO=$4

if [[ "$WRITE" != "yes" ]] && [[ "$WRITE" != "no" ]]; then
	echo "Arg 1 must be yes or no"
	exit 1
fi

for f in "${@:5}"; do
	metaflac --show-tag="$TAG" "$f" > "$TMPFILE"
	
	if [[ "$WRITE" == "yes" ]]; then
		metaflac --show-tag="$TAG" "$f" > "$TMPFILE"
		metaflac --remove-tag="$TAG" "$f"
		metaflac --import-tags-from=<(sed "s/$FROM/$TO/" < "$TMPFILE") "$f"
	else
		grep "$TAG" $TMPFILE | while read line; do
			echo changing "$line" to $(echo "$line" | sed "s/$FROM/$TO/")
		done
	fi
done
